// Auto-generated by rust/heart_rgb_matrix_driver/tools/generate_pi5_pio_programs.py.
#![allow(dead_code)]

pub(crate) const PI5_PIO_SIMPLE_HUB75_PROGRAM_LENGTH: usize = 8;
pub(crate) const PI5_PIO_SIMPLE_HUB75_WRAP_TARGET: u8 = 0;
pub(crate) const PI5_PIO_SIMPLE_HUB75_WRAP: u8 = 4;
pub(crate) const PI5_PIO_SIMPLE_HUB75_SIDESET_PIN_COUNT: u8 = 1;
pub(crate) const PI5_PIO_SIMPLE_HUB75_SIDESET_OPTIONAL: bool = true;
pub(crate) const PI5_PIO_SIMPLE_HUB75_SIDESET_TOTAL_BITS: u8 = 2;
pub(crate) const PI5_PIO_SIMPLE_HUB75_OUT_PIN_BASE: u8 = 0;
pub(crate) const PI5_PIO_SIMPLE_HUB75_OUT_PIN_COUNT: u8 = 28;
pub(crate) const PI5_PIO_SIMPLE_HUB75_OUT_SHIFT_RIGHT: bool = false;
pub(crate) const PI5_PIO_SIMPLE_HUB75_AUTO_PULL: bool = true;
pub(crate) const PI5_PIO_SIMPLE_HUB75_PULL_THRESHOLD: u8 = 32;
pub(crate) const PI5_PIO_SIMPLE_HUB75_DELAY_PATCH_INDICES: [usize; 2] = [3, 4];
pub(crate) const PI5_PIO_SIMPLE_HUB75_BASE_PROGRAM: [u16; 8] = [
    0x6021, 0x605f, 0x0025, 0x6000, 0x1883, 0x6000, 0x0086, 0x0000,
];

pub(crate) const PI5_PIO_RESIDENT_PARSER_PROGRAM_LENGTH: usize = 26;
pub(crate) const PI5_PIO_RESIDENT_PARSER_WRAP_TARGET: u8 = 0;
pub(crate) const PI5_PIO_RESIDENT_PARSER_WRAP: u8 = 25;
pub(crate) const PI5_PIO_RESIDENT_PARSER_SIDESET_PIN_COUNT: u8 = 1;
pub(crate) const PI5_PIO_RESIDENT_PARSER_SIDESET_OPTIONAL: bool = true;
pub(crate) const PI5_PIO_RESIDENT_PARSER_SIDESET_TOTAL_BITS: u8 = 2;
pub(crate) const PI5_PIO_RESIDENT_PARSER_OUT_PIN_BASE: u8 = 5;
pub(crate) const PI5_PIO_RESIDENT_PARSER_OUT_PIN_COUNT: u8 = 23;
pub(crate) const PI5_PIO_RESIDENT_PARSER_OUT_SHIFT_RIGHT: bool = false;
pub(crate) const PI5_PIO_RESIDENT_PARSER_AUTO_PULL: bool = true;
pub(crate) const PI5_PIO_RESIDENT_PARSER_PULL_THRESHOLD: u8 = 23;
pub(crate) const PI5_PIO_RESIDENT_PARSER_DELAY_PATCH_INDICES: [usize; 3] = [2, 18, 19];
pub(crate) const PI5_PIO_RESIDENT_PARSER_BASE_PROGRAM: [u16; 26] = [
    0x80a0, 0x7017, 0xb042, 0x80a0, 0x6021, 0x002b, 0x6048, 0xa027, 0xb001, 0x1888, 0x1003, 0x6048,
    0x6037, 0x0032, 0xb0e1, 0x7017, 0x188f, 0x1003, 0xf001, 0xf000, 0x90a0, 0x7017, 0x90a0, 0x7040,
    0x1098, 0x1000,
];
