[program:heart-xvfb]
command=/usr/local/bin/heart-supervisor-xvfb.sh
priority=10
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/var/log/heart/xvfb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/heart/xvfb.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:heart-app]
command=/usr/local/bin/heart-supervisor-app.sh
priority=20
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/heart/heart-app.log
stderr_logfile=/var/log/heart/heart-app.err.log

[program:heart-manyfold-signer]
command=/usr/local/bin/heart-supervisor-signer.sh
priority=15
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/heart/manyfold-signer.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/heart/manyfold-signer.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:heart-rp1-scanner]
command=/usr/local/bin/heart-supervisor-rp1-scanner.sh
priority=30
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/heart/rp1-scanner.log
stderr_logfile=/var/log/heart/rp1-scanner.err.log
