# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart/peripheral/proto/peripheral_payloads.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0heart/peripheral/proto/peripheral_payloads.proto\x12\x19heart.peripheral.payloads\"9\n\x10PeripheralStatus\x12\x15\n\rperipheral_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heart.peripheral.proto.peripheral_payloads_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERIPHERALSTATUS._serialized_start=79
  _PERIPHERALSTATUS._serialized_end=136
# @@protoc_insertion_point(module_scope)
