from heart.peripheral.core.providers import register_provider
from heart.renderers.water_cube.provider import WaterCubeStateProvider

register_provider(WaterCubeStateProvider, WaterCubeStateProvider)
