CIRCUIT_PY_BOOT_NAME="TRINKEYBOOT"
CIRCUIT_PY_UF2_URL="https://downloads.circuitpython.org/bin/adafruit_rotary_trinkey_m0/en_US/adafruit-circuitpython-adafruit_rotary_trinkey_m0-en_US-9.2.0.uf2"
CIRCUIT_PY_UF2_CHECKSUM="de0720c3a89721d97e5d3e3a3c7797a4c962a958daab0ba6819c696bf818275e"
VALID_BOARD_IDS="adafruit_rotary_trinkey_m0"
CIRCUIT_PY_DRIVER_LIBS=""