# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart/device/beats/proto/beats_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.heart/device/beats/proto/beats_streaming.proto\x12\x15heart.beats.streaming\"\xa5\x01\n\rPeripheralTag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07variant\x18\x02 \x01(\t\x12\x44\n\x08metadata\x18\x03 \x03(\x0b\x32\x32.heart.beats.streaming.PeripheralTag.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\x0ePeripheralInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x32\n\x04tags\x18\x02 \x03(\x0b\x32$.heart.beats.streaming.PeripheralTag\"j\n\x12PeripheralEnvelope\x12>\n\x0fperipheral_info\x18\x01 \x01(\x0b\x32%.heart.beats.streaming.PeripheralInfo\x12\x14\n\x0cjson_payload\x18\x02 \x01(\t\"\x19\n\x05\x46rame\x12\x10\n\x08png_data\x18\x01 \x01(\x0c\"\x8b\x01\n\x0eStreamEnvelope\x12-\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x1c.heart.beats.streaming.FrameH\x00\x12?\n\nperipheral\x18\x02 \x01(\x0b\x32).heart.beats.streaming.PeripheralEnvelopeH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heart.device.beats.proto.beats_streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERIPHERALTAG_METADATAENTRY._options = None
  _PERIPHERALTAG_METADATAENTRY._serialized_options = b'8\001'
  _PERIPHERALTAG._serialized_start=74
  _PERIPHERALTAG._serialized_end=239
  _PERIPHERALTAG_METADATAENTRY._serialized_start=192
  _PERIPHERALTAG_METADATAENTRY._serialized_end=239
  _PERIPHERALINFO._serialized_start=241
  _PERIPHERALINFO._serialized_end=321
  _PERIPHERALENVELOPE._serialized_start=323
  _PERIPHERALENVELOPE._serialized_end=429
  _FRAME._serialized_start=431
  _FRAME._serialized_end=456
  _STREAMENVELOPE._serialized_start=459
  _STREAMENVELOPE._serialized_end=598
# @@protoc_insertion_point(module_scope)
