# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heart/device/beats/proto/beats_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heart/device/beats/proto/beats_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.heart/device/beats/proto/beats_streaming.proto\x12\x15heart.beats.streaming\"\xa5\x01\n\rPeripheralTag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07variant\x18\x02 \x01(\t\x12\x44\n\x08metadata\x18\x03 \x03(\x0b\x32\x32.heart.beats.streaming.PeripheralTag.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x12PeripheralLocation\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0c\n\x04time\x18\x04 \x01(\t\"\x8d\x01\n\x0ePeripheralInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x32\n\x04tags\x18\x02 \x03(\x0b\x32$.heart.beats.streaming.PeripheralTag\x12;\n\x08location\x18\x03 \x01(\x0b\x32).heart.beats.streaming.PeripheralLocation\"\xc7\x01\n\x12PeripheralEnvelope\x12>\n\x0fperipheral_info\x18\x01 \x01(\x0b\x32%.heart.beats.streaming.PeripheralInfo\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12J\n\x10payload_encoding\x18\x03 \x01(\x0e\x32\x30.heart.beats.streaming.PeripheralPayloadEncoding\x12\x14\n\x0cpayload_type\x18\x04 \x01(\t\"\x19\n\x05\x46rame\x12\x10\n\x08png_data\x18\x01 \x01(\x0c\"\x8b\x01\n\x0eStreamEnvelope\x12-\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x1c.heart.beats.streaming.FrameH\x00\x12?\n\nperipheral\x18\x02 \x01(\x0b\x32).heart.beats.streaming.PeripheralEnvelopeH\x00\x42\t\n\x07payload*e\n\x19PeripheralPayloadEncoding\x12+\n\'PERIPHERAL_PAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12\r\n\tJSON_UTF8\x10\x01\x12\x0c\n\x08PROTOBUF\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heart.device.beats.proto.beats_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERIPHERALTAG_METADATAENTRY']._loaded_options = None
  _globals['_PERIPHERALTAG_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PERIPHERALPAYLOADENCODING']._serialized_start=825
  _globals['_PERIPHERALPAYLOADENCODING']._serialized_end=926
  _globals['_PERIPHERALTAG']._serialized_start=74
  _globals['_PERIPHERALTAG']._serialized_end=239
  _globals['_PERIPHERALTAG_METADATAENTRY']._serialized_start=192
  _globals['_PERIPHERALTAG_METADATAENTRY']._serialized_end=239
  _globals['_PERIPHERALLOCATION']._serialized_start=241
  _globals['_PERIPHERALLOCATION']._serialized_end=308
  _globals['_PERIPHERALINFO']._serialized_start=311
  _globals['_PERIPHERALINFO']._serialized_end=452
  _globals['_PERIPHERALENVELOPE']._serialized_start=455
  _globals['_PERIPHERALENVELOPE']._serialized_end=654
  _globals['_FRAME']._serialized_start=656
  _globals['_FRAME']._serialized_end=681
  _globals['_STREAMENVELOPE']._serialized_start=684
  _globals['_STREAMENVELOPE']._serialized_end=823
# @@protoc_insertion_point(module_scope)
