/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamIndexRouteImport } from './routes/stream/index'
import { Route as MissionControlIndexRouteImport } from './routes/mission-control/index'
import { Route as PeripheralsEventsRouteImport } from './routes/peripherals/events'
import { Route as PeripheralsConnectedRouteImport } from './routes/peripherals/connected'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamIndexRoute = StreamIndexRouteImport.update({
  id: '/stream/',
  path: '/stream/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlIndexRoute = MissionControlIndexRouteImport.update({
  id: '/mission-control/',
  path: '/mission-control/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeripheralsEventsRoute = PeripheralsEventsRouteImport.update({
  id: '/peripherals/events',
  path: '/peripherals/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PeripheralsConnectedRoute = PeripheralsConnectedRouteImport.update({
  id: '/peripherals/connected',
  path: '/peripherals/connected',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mission-control': typeof MissionControlIndexRoute
  '/peripherals/connected': typeof PeripheralsConnectedRoute
  '/peripherals/events': typeof PeripheralsEventsRoute
  '/stream': typeof StreamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mission-control': typeof MissionControlIndexRoute
  '/peripherals/connected': typeof PeripheralsConnectedRoute
  '/peripherals/events': typeof PeripheralsEventsRoute
  '/stream': typeof StreamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mission-control/': typeof MissionControlIndexRoute
  '/peripherals/connected': typeof PeripheralsConnectedRoute
  '/peripherals/events': typeof PeripheralsEventsRoute
  '/stream/': typeof StreamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mission-control'
    | '/peripherals/connected'
    | '/peripherals/events'
    | '/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mission-control' | '/peripherals/connected' | '/peripherals/events' | '/stream'
  id:
    | '__root__'
    | '/'
    | '/mission-control/'
    | '/peripherals/connected'
    | '/peripherals/events'
    | '/stream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionControlIndexRoute: typeof MissionControlIndexRoute
  PeripheralsConnectedRoute: typeof PeripheralsConnectedRoute
  PeripheralsEventsRoute: typeof PeripheralsEventsRoute
  StreamIndexRoute: typeof StreamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control/': {
      id: '/mission-control/'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/': {
      id: '/stream/'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peripherals/events': {
      id: '/peripherals/events'
      path: '/peripherals/events'
      fullPath: '/peripherals/events'
      preLoaderRoute: typeof PeripheralsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peripherals/connected': {
      id: '/peripherals/connected'
      path: '/peripherals/connected'
      fullPath: '/peripherals/connected'
      preLoaderRoute: typeof PeripheralsConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionControlIndexRoute: MissionControlIndexRoute,
  PeripheralsConnectedRoute: PeripheralsConnectedRoute,
  PeripheralsEventsRoute: PeripheralsEventsRoute,
  StreamIndexRoute: StreamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
