class SceneSnapshot:
    active_scene_index: int
    active_scene_name: str
    current_button_value: int
    offset_button_value: int | None
    scene_count: int


class SceneManagerBridge:
    def __init__(self, scene_names: list[str]) -> None: ...
    def active_scene_index(self, current_button_value: int) -> int: ...
    def register_scene(self, scene_name: str) -> None: ...
    def reset_button_offset(self, current_button_value: int) -> None: ...
    def scene_count(self) -> int: ...
    def scene_names(self) -> list[str]: ...
    def snapshot(self, current_button_value: int) -> SceneSnapshot: ...


class SoftwareSceneBuffer:
    height: int
    width: int

    def __init__(self, width: int, height: int) -> None: ...
    def blit(
        self,
        source: SoftwareSceneBuffer,
        dest: tuple[int, int] = (0, 0),
        area: tuple[int, int, int, int] | None = None,
    ) -> None: ...
    def blit_array(
        self,
        array,
        dest: tuple[int, int] = (0, 0),
    ) -> None: ...
    def channels(self) -> int: ...
    def fill_rect_rgba(
        self,
        red: int,
        green: int,
        blue: int,
        alpha: int = 255,
        rect: tuple[int, int, int, int] | None = None,
    ) -> None: ...
    def fill_rgba(
        self,
        red: int,
        green: int,
        blue: int,
        alpha: int = 255,
    ) -> None: ...
    def get_height(self) -> int: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_width(self) -> int: ...
    def rgba_array(self): ...
    @staticmethod
    def from_safetensors(buffer: bytes) -> SoftwareSceneBuffer: ...
    def to_safetensors(self) -> bytes: ...


def bridge_version() -> str: ...
