class SceneSnapshot:
    active_scene_index: int
    active_scene_name: str
    current_button_value: int
    offset_button_value: int | None
    scene_count: int


class SceneManagerBridge:
    def __init__(self, scene_names: list[str]) -> None: ...
    def active_scene_index(self, current_button_value: int) -> int: ...
    def register_scene(self, scene_name: str) -> None: ...
    def reset_button_offset(self, current_button_value: int) -> None: ...
    def scene_count(self) -> int: ...
    def scene_names(self) -> list[str]: ...
    def snapshot(self, current_button_value: int) -> SceneSnapshot: ...


def bridge_version() -> str: ...
